config/routes.rb
ASIPract::Application.routes.draw do
  
  devise_for :users

  resources :tickets

  root :to => "tickets#index"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role? :administrador
      can :manage, :all
    elsif user.role? :tecnico
      can :update, :all
      can :read, :all 
    else
      can :read, :all
      can :create, Ticket
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/historico.rb
class Historico < ActiveRecord::Base
  belongs_to :ticket
  attr_accessible :nota, :usuario_encargado
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :historicos
  
  accepts_nested_attributes_for :historicos, :allow_destroy => true, :reject_if => :all_blank
  
  attr_accessible :creador, :descripcion, :estado, :prioridad, :tecnico_asignado, :titulo, :historicos_attributes, :user_id
  
  PRIORIDAD = %w[inmediata alta normal baja]
  REALIZADO = %w[inicio asignado en_proceso cerrado]
  
  def self.search(query)
     # where(:title, query) -> This would return an exact match of the query
     where("id like ?", "%#{query}%")
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body
  
  validates_presence_of :username
  
  ROLES = %w[administrador tecnico paciente]
  
  def role_symbols
    [role.to_sym]
  end
  
  def role?(role)
    self.role == role.to_s 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  def index
    
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  load_and_authorize_resource
  
  # GET /tickets
  # GET /tickets.json
  def index
    if params[:search]
      if current_user.role? :administrador
        @tickets = Ticket.search(params[:search]).order(params[:sort])
      elsif current_user.role? :paciente
        @tickets = Ticket.search(params[:search]).where(user_id: current_user).order(params[:sort])
      else
        @tickets = Ticket.search(params[:search]).where(tecnico_asignado: current_user).order(params[:sort])
      end
     else
       if current_user.role? :administrador
         @tickets = Ticket.find(:all, order: params[:sort])
       elsif current_user.role? :paciente
         @tickets = Ticket.where(user_id: current_user).order(params[:sort])
       else
         @tickets = Ticket.where(tecnico_asignado: current_user).order(params[:sort])
       end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    if !@ticket.tecnico_asignado.nil?
      @user = User.where(role: "tecnico").where(id: @ticket.tecnico_asignado)
      @user = @user.first.username
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new
    @ticket.historicos.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
    @ticket.historicos.new
    @user = User.where(role: "tecnico")
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket creado.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])
    @user = User.all

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
      new_object = f.object.send(association).klass.new
      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|
        render(association.to_s.singularize + "_fields", f: builder)
      end
      link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def tecnico(ticket)
    user = User.where(role: "tecnico").where(id: ticket.to_i)
    user = user.first.username
    return user
  end
end

app/views/home/index.html.erb
TICKETS

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gestión de incidencias</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
	<div class="contenedor-principal">
  
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Hospital Comarcal</a>
        </div>
        <!-- Top Menu Items -->
            <div class="sessiones pull-right">
                  <% if user_signed_in? %>
                    <span class="usuario">Bienvenido <%= current_user.username %></span> <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "btn btn-mini btn-danger logout") %>
                    <% else %>
                    <%= link_to('Entrar', new_user_session_path, :class => "btn btn-mini")  %> <%= link_to('Registrarse', new_user_registration_path, :class => "btn btn-mini")  %> 
                  <% end %>
             </div>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    </nav>
    
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    
    <%= yield %>
    <br><br><br>
        <footer>
            <p>&copy; Practica ASI 2015</p>
        </footer>
  </div>
        
</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo, :class => "span12" %>
  </div><br />
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion, :class => 'text_field span12', :size => "x10" %>
  </div>
  <% if f.object.creador.blank? %>
    <%= f.hidden_field :creador, :value => current_user.username %>
  <% end %>
  <br />
  <% if f.object.user_id.blank? %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <% end %>

  <% if current_user.role? :administrador %>
  <div class="field">
    <%= f.label :tecnico_asignado %><br />
    <%= f.collection_select :tecnico_asignado, User.where(role: "tecnico"), :id, :username %>
  </div><br />
  
  <div class="field">
    <%= f.label :prioridad %><br />
    <%= f.collection_select :prioridad, Ticket::PRIORIDAD, :to_s, :humanize %>
  </div><br />
  <% end %>

  <% if current_user.role? :tecnico or current_user.role? :administrador %>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.collection_select :estado, Ticket::REALIZADO, :to_s, :humanize %>
  </div><br /><br />
  <% end %>
  
 <% if !(controller.action_name == "new") %>
  <% if !current_user.role? :paciente %>
      <div class="nested-forms">
        <%= f.simple_fields_for :historicos do |n| %>
        <div class="nested-form <%= 'nested-form-template' if !n.object.persisted? and n.object.errors.empty? %>">
          <% if n.object.usuario_encargado.blank? %>
            <%= n.hidden_field :usuario_encargado, :value => current_user.username %>
          <% end %>
          <% if n.object.nota.blank? %>
          <%= n.input :nota, label: "Nota", :input_html => { :class => 'text_field span12', :size => "x4"} %>
          <% else %>
          <%= n.input :nota, label: "Nota", :input_html => { :class => 'text_field span12', :disabled => "true", :size => "x4"} %>
          <% end %>
          <% if can? :manage, :historicos %>
           <a href="#" class="btn btn-danger nested-form-remove offset10">Borrar nota</a>
           <% end %>
           <br>
          <hr>
        </div>
    <% end %>

        <a href="#" class="btn btn-success nested-form-add">Añadir Nota</a>
        
 <% end %>
    <% end %><br><br>

  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %> | <%= link_to "Atrás" , tickets_path, :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editar ticket</h1>

<%= render 'form' %>

app/views/tickets/index.html.erb
<h1>Listado de tickets asociados</h1>

  <%= form_tag(tickets_path, :method => "get", id: "search-form") do %>
    <div class="input-group span3 pull-right">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar ID" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
        <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Buscar!</button>
        </span>
    </div>
  <% end %>

<% if !current_user.role? :tecnico %>
  <%= link_to 'Nuevo Ticket', new_ticket_path, :class => "btn btn-info" %>
<% end %><br><br>

<table class="table table-striped">
 <thead>
  <tr>
    <th><%= link_to "ID", :sort => "ID" %></th>
    <th><%= link_to "Titulo", :sort => "titulo" %></th>
    <th><%= link_to "Creador", :sort => "creador"%></th>
    <th><%= link_to "Asignado a", :sort => "tecnico_asignado"%></th>
    <th><%= link_to "Prioridad", :sort => "prioridad"%></th>
    <th><%= link_to "Estado", :sort => "estado"%></th>
    <th> Creada</th>
    <th> Acciones</th>
  </tr>
 </thead>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.id%></td>
    <td><%= link_to ticket.titulo, ticket %></td>
    <td><%= ticket.creador %></td>
    <td><%= tecnico(ticket.tecnico_asignado) unless ticket.tecnico_asignado.nil? %>
    <td><%= ticket.prioridad %></td>
    <td><%= ticket.estado %></td>
    <td><%= ticket.created_at.strftime("%d/%m/%Y %H:%M") %>h</td>
    <td><%= link_to 'Mostar', ticket, :class => "btn btn-xs btn-primary" %>
    <% if can? :update, @ticket%>
      <%= link_to 'Editar', edit_ticket_path(ticket), :class => "btn btn-xs btn-success" %>
    <% end %>
    <% if can? :destroy, @ticket%>
      <%= link_to 'Eliminar', ticket, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-danger" %>
    <% end %></td>
  </tr>
<% end %>
</table>

<br />

<% if !current_user.role? :tecnico %>
  <%= link_to 'Nuevo Ticket', new_ticket_path, :class => "btn btn-info" %>
<% end %>

app/views/tickets/new.html.erb
<h1>Nuevo ticket</h1><hr>

<%= render 'form' %>

app/views/tickets/show.html.erb
<h1>Ticket <%= @ticket.id%></h1>

<p id="notice"><%= notice %></p>

<% if can? :read, @ticket%>
<div class="bs-callout bs-callout-warning">
  <b>Titulo:</b><br>
  <%= @ticket.titulo %>
</div>

<div class="bs-callout bs-callout-warning">
  <b>Descripcion:</b><br>
  <%= @ticket.descripcion %>
</div>

<div class="bs-callout bs-callout-warning">
  <b>Creador:</b><br>
  <%= @ticket.creador %>
</div>
<% end %>

<%if can? :upadte, @tickets %>
<div class="bs-callout bs-callout-warning">
  <b>Tecnico asignado:</b><br>
  <%= @user %>
</div>

<div class="bs-callout bs-callout-warning">
    <b>Prioridad:</b><br>
    <%= @ticket.prioridad %>
</div>

<div class="bs-callout bs-callout-warning">
  <b>Estado:</b><br>
  <%= @ticket.estado %>
</div>
<% end %>

<h3>Historico</h3><hr>

<% if @ticket.historicos.size > 0%>
    <div class="nested-forms">
      <% @ticket.historicos.each do |n| %>
      <% if !n.nota.blank? %>
      <div class="form-actions">
       <dl class="dl-horizontal">
          <dt>Actualizado por
            <dd><%= n.usuario_encargado %> el <%= n.updated_at.strftime("%d/%m/%Y a las %H:%M")%>h</dd>
          <dt><strong>Notas</strong></dt>
            <dd><%= n.nota %></dd>
        </dl>
        </div>
        <% end %>
      <% end %>
      </div>
<% end %>


<% if can? :update, @ticket%>
  <%= link_to 'Editar', edit_ticket_path(@ticket), :class => "btn btn-primary" %> |
<% end %>
<%= link_to 'Atrás', tickets_path, :class => "btn btn-primary btn-warning" %>